### ISSUE TITLE
Doesn't build with polkit-qt 0.113

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dde-polkit-agent#26]
```
policykitlistener.cpp: In member function ‘void PolicyKitListener::fillResult()’:
policykitlistener.cpp:326:41: error: ‘class PolkitQt1::Agent::AsyncResult’ has no member named ‘setCancel’
  326 |             m_session.data()->result()->setCancel("aciton cancel");
      |                                         ^~~~~~~~~
policykitlistener.cpp:333:23: error: ‘class PolkitQt1::Agent::AsyncResult’ has no member named ‘setCancel’
  333 |             m_result->setCancel("action cancel");
      |                       ^~~~~~~~~
```

**Comment by hillwoodroc** [comment]
Same as openSUSE Tumbleweed:
```
[   67s] g++ -c -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -DOPENSSL_LOAD_CONF -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DQ_HOST_NAME=\"x86_64\" -DQ_HOST_X86_64 -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I/usr/include/polkit-qt5-1 -I/usr/include/qt5/QtCore -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/libdframeworkdbus-2.0 -I/usr/include/qt5/QGSettings -I/usr/include/libdtk-5.0.0/DWidget -I/usr/include/libdtk-5.0.0/DCore -I/usr/include/libdtk-5.0.0/DGui -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtDBus -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o policykitlistener.o policykitlistener.cpp
[   67s] policykitlistener.cpp: In member function 'void PolicyKitListener::fillResult()':
[   67s] policykitlistener.cpp:326:41: error: 'class PolkitQt1::Agent::AsyncResult' has no member named 'setCancel'
[   67s]   326 |             m_session.data()->result()->setCancel("aciton cancel");
[   67s]       |                                         ^~~~~~~~~
[   67s] policykitlistener.cpp:333:23: error: 'class PolkitQt1::Agent::AsyncResult' has no member named 'setCancel'
[   67s]   333 |             m_result->setCancel("action cancel");
[   67s]       |                       ^~~~~~~~~
[   67s] make: *** [Makefile:515: policykitlistener.o] Error 1
[   67s] make: *** Waiting for unfinished jobs....

```

**Comment by justforlxz** [comment]
https://invent.kde.org/libraries/polkit-qt-1/-/merge_requests/7  已允许合并，但没有权限。
