### ISSUE TITLE
Does not build with dtkwidget-2.0.9.9

### ISSUE THREAD

**Issue by romildo** [linuxdeepin/dde-polkit-agent#3]
Building fails on NixOS with the error message:

```
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -isystem /nix/store/r3k1i26b2ijb9b8149fjyxjmhza8ymlq-dtkcore-2.0.9.8/include/libdtk-2.0.6/DCore -isystem /nix/store/ij6wy61j2kldah0md0hcamndjcv46ick-dtkwidget-2.0.9.9/include/DWidget -isystem /nix/store/yd5wgc2yaz8biynyjxsh743xyh7bnr77-qtbase-5.11.1-dev/include/QtGui -isystem /nix/store/yd5wgc2yaz8biynyjxsh743xyh7bnr77-qtbase-5.11.1-dev/include -isystem /nix/store/yd5wgc2yaz8biynyjxsh743xyh7bnr77-qtbase-5.11.1-dev/include/QtCore -isystem /nix/store/skg6412afdv4gs6zrcx0k96da02zara2-polkit-qt-1-qt5-0.112.0-dev/include/polkit-qt5-1 -isystem /nix/store/xph96m4b49drqwvkpcsj6dhkzdg8wgyh-dde-qt-dbus-factory-1.0.5/include/libdframeworkdbus-2.0 -isystem /nix/store/yd5wgc2yaz8biynyjxsh743xyh7bnr77-qtbase-5.11.1-dev/include/QtWidgets -isystem /nix/store/yd5wgc2yaz8biynyjxsh743xyh7bnr77-qtbase-5.11.1-dev/include/QtDBus -I. -I/nix/store/3jkazlcyhqss2kyy385ajhy6jcwzxdpk-mesa-noglu-18.2.2-dev/include -I/nix/store/yd5wgc2yaz8biynyjxsh743xyh7bnr77-qtbase-5.11.1-dev/mkspecs/linux-g++ -o policykitlistener.o policykitlistener.cpp
In file included from policykitlistener.cpp:30:0:
AuthDialog.h:25:10: fatal error: dcombobox.h: No such file or directory
 #include <dcombobox.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:501: policykitlistener.o] Error 1
```

**Comment by 1dot75cm** [comment]
```
sed -i 's|dcombobox.h|QComboBox|' AuthDialog.h
```

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
